// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwyvxnwweagcfkgmmdmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13eXZ4bnd3ZWFnY2ZrZ21tZG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5ODk1NDMsImV4cCI6MjA3NjU2NTU0M30.3mZaUrha91ZB5zWi0XU9T2IeLBGZOuFIMCiUL_41sKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});